/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/UserPresence": {
    get: operations["UserPresence_GetClientUserPresenceQuery"];
    put: operations["UserPresence_PutGetClientUserPresenceQuery"];
  };
}

export interface components {
  schemas: {
    PaginatedListOfPresenceUserStateDto: {
      items?: components["schemas"]["PresenceUserStateDto"][];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      totalCount?: number;
      hasPreviousPage?: boolean;
      hasNextPage?: boolean;
    };
    PresenceUserStateDto: {
      externalIds?: { [key: string]: string };
      availability?: string;
      activity?: string;
      /** Format: date-time */
      returnTime?: string | null;
      status?: string | null;
      idle?: boolean;
      /** Format: date-time */
      idleSince?: string | null;
    };
    ClientUserId: {
      type?: string;
      externalUserId?: string;
    };
    GetClientUserPresenceQuery: {
      clients?: components["schemas"]["ClientUserId"][];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
    };
  };
}

export interface operations {
  UserPresence_GetClientUserPresenceQuery: {
    parameters: {
      query: {
        Clients?: components["schemas"]["ClientUserId"][] | null;
        PageNumber?: number;
        PageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedListOfPresenceUserStateDto"];
        };
      };
    };
  };
  UserPresence_PutGetClientUserPresenceQuery: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedListOfPresenceUserStateDto"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetClientUserPresenceQuery"];
      };
    };
  };
}

export interface external {}
